name: hummingbot-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - boto3
  - libcxx                
  - python-dotenv
  - pandas=2.3.2
  - numpy>=2.2.6       
  - pandas-ta>=0.4.71b  
  - docker-py
  - pip
  - pip:
      - hummingbot    
      - msgpack>=1.0.5
      - flake8
      - isort
      - pre-commit
      - logfire
      - logfire[fastapi]
      - logfire[system-metrics]
      - aiomqtt>=2.0.0
      - sqlalchemy>=2.0.0
      - asyncpg
      - psycopg2-binary
      - greenlet
      - pydantic-settings
