.PHONY: setup run run-https deploy stop install uninstall build install-pre-commit generate-certs show-certs

SETUP_SENTINEL := .setup-complete

setup: $(SETUP_SENTINEL)

$(SETUP_SENTINEL):
	chmod +x setup.sh
	./setup.sh

# Run locally (dev mode) — auto-switches to HTTPS if SSL_ENABLED=true in .env
run:
	docker compose up emqx postgres -d
	@set -a; [ -f .env ] && . ./.env; set +a; \
	if [ "$${SSL_ENABLED:-false}" = "true" ]; then \
		CERT_PATH=$${SSL_CERT_PATH:-./certs/server.pem}; \
		KEY_PATH=$${SSL_KEY_PATH:-./certs/server.key}; \
		PORT=$${SSL_PORT:-8443}; \
		if [ ! -f "$$CERT_PATH" ] || [ ! -f "$$KEY_PATH" ]; then \
			echo "SSL_ENABLED=true but cert/key not found. Run 'make generate-certs' first."; \
			echo "Expected cert: $$CERT_PATH"; \
			echo "Expected key:  $$KEY_PATH"; \
			exit 1; \
		fi; \
		conda run --no-capture-output -n hummingbot-api uvicorn main:app --reload --host 0.0.0.0 --port $$PORT --ssl-certfile "$$CERT_PATH" --ssl-keyfile "$$KEY_PATH"; \
	else \
		conda run --no-capture-output -n hummingbot-api uvicorn main:app --reload; \
	fi

# Run locally with HTTPS (requires certs generated by setup.sh or generate-certs)
run-https:
	docker compose up emqx postgres -d
	@set -a; [ -f .env ] && . ./.env; set +a; \
	CERT_PATH=$${SSL_CERT_PATH:-./certs/server.pem}; \
	KEY_PATH=$${SSL_KEY_PATH:-./certs/server.key}; \
	PORT=$${SSL_PORT:-8443}; \
	if [ ! -f "$$CERT_PATH" ] || [ ! -f "$$KEY_PATH" ]; then \
		echo "Missing SSL cert/key. Run 'make generate-certs' first."; \
		echo "Expected cert: $$CERT_PATH"; \
		echo "Expected key:  $$KEY_PATH"; \
		exit 1; \
	fi; \
	conda run --no-capture-output -n hummingbot-api uvicorn main:app --reload --host 0.0.0.0 --port $$PORT --ssl-certfile "$$CERT_PATH" --ssl-keyfile "$$KEY_PATH"

# Deploy with Docker
deploy: $(SETUP_SENTINEL)
	docker compose up -d

# Stop all services
stop:
	docker compose down

# Install conda environment
install:
	@if ! command -v conda >/dev/null 2>&1; then \
		echo "Error: Conda is not found in PATH. Please install Conda or add it to your PATH."; \
		exit 1; \
	fi
	@if conda env list | grep -q '^hummingbot-api '; then \
		echo "Environment already exists."; \
	else \
		conda env create -f environment.yml; \
	fi
	$(MAKE) install-pre-commit
	$(MAKE) setup

uninstall:
	conda env remove -n hummingbot-api -y
	rm -f $(SETUP_SENTINEL)

install-pre-commit:
	conda run -n hummingbot-api pip install pre-commit
	conda run -n hummingbot-api pre-commit install

# Re-run setup and force interactive certificate workflow
generate-certs:
	chmod +x setup.sh
	./setup.sh --certs-only

# Show configured SSL cert paths and file existence
show-certs:
	@set -e; \
	ENV_FILE=".env"; \
	if [ -f "$$ENV_FILE" ]; then \
		SSL_CERT_PATH=$$(grep '^SSL_CERT_PATH=' "$$ENV_FILE" | tail -n1 | cut -d= -f2-); \
		SSL_KEY_PATH=$$(grep '^SSL_KEY_PATH=' "$$ENV_FILE" | tail -n1 | cut -d= -f2-); \
		SSL_CA_PATH=$$(grep '^SSL_CA_PATH=' "$$ENV_FILE" | tail -n1 | cut -d= -f2-); \
		SSL_CLIENT_CERT_PATH=$$(grep '^SSL_CLIENT_CERT_PATH=' "$$ENV_FILE" | tail -n1 | cut -d= -f2-); \
		SSL_CLIENT_KEY_PATH=$$(grep '^SSL_CLIENT_KEY_PATH=' "$$ENV_FILE" | tail -n1 | cut -d= -f2-); \
	else \
		SSL_CERT_PATH=""; SSL_KEY_PATH=""; SSL_CA_PATH=""; SSL_CLIENT_CERT_PATH=""; SSL_CLIENT_KEY_PATH=""; \
	fi; \
	SSL_CERT_PATH=$${SSL_CERT_PATH:-./certs/server.pem}; \
	SSL_KEY_PATH=$${SSL_KEY_PATH:-./certs/server.key}; \
	SSL_CA_PATH=$${SSL_CA_PATH:-./certs/ca.pem}; \
	SSL_CLIENT_CERT_PATH=$${SSL_CLIENT_CERT_PATH:-./certs/client.pem}; \
	SSL_CLIENT_KEY_PATH=$${SSL_CLIENT_KEY_PATH:-./certs/client.key}; \
	check_file() { \
		LABEL="$$1"; \
		PATH_VALUE="$$2"; \
		if [ -f "$$PATH_VALUE" ]; then \
			echo "$$LABEL: $$PATH_VALUE [FOUND]"; \
		else \
			echo "$$LABEL: $$PATH_VALUE [MISSING]"; \
		fi; \
	}; \
	echo "Hummingbot API SSL certificate paths"; \
	echo ""; \
	check_file "CA bundle" "$$SSL_CA_PATH"; \
	check_file "Server cert" "$$SSL_CERT_PATH"; \
	check_file "Server key" "$$SSL_KEY_PATH"; \
	check_file "Client cert (mTLS)" "$$SSL_CLIENT_CERT_PATH"; \
	check_file "Client key (mTLS)" "$$SSL_CLIENT_KEY_PATH"

# Build Docker image
build:
	docker build -t hummingbot/hummingbot-api:latest .